name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed

permissions:
  contents: write  # ✅ This gives GitHub Actions permission to push to your repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Report Generator
        run: python generate_report.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Built-in token with correct access
          publish_dir: ./                            # 📁 deploy the current folder (index.html is here)
