# .github/workflows/python-ci.yml

name: Python CI

on:
  push:
    branches:
        - master
  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]  # Test on multiple Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: check version
        run: python --version

      - name: Run Python script
        run: python test_main.py    
